name: DPLK-SignShop
version: 1.0
main: com.github.licker2689.dplksignshop.DPLKSignShop
api-version: 1.19
authors: [ darksoldier1404, LICKER2689 ]
depend:
  - DPP-Core
  - DP-SimpleShop
commands:
  표지판 상점:
    aliases: [dlss]
